const ActionsConst = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    GET_PRODUCTS_FROM_LS: 'GET_PRODUCTS_FROM_LS',
    TOGGLE_FAVOURITES: 'TOGGLE_FAVOURITES',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    DECREASE_AMOUNT_IN_CART:'DECREASE_AMOUNT_IN_CART',
    CLEAN_CART:'CLEAN_CART'
};
export default ActionsConst;